### ISSUE TITLE
📝 Specify additional commands in the `developing` page

### ISSUE THREAD

**Issue by willser** [neon-mmd/websurfx#377]
### Description

Hello team,

https://github.com/neon-mmd/websurfx/blob/3189de6fb9bc40afd7d18e82213b88d5f0253a0a/docs/developing.md?plain=1#L55-L57

Above command seem not enough for a new to stylelint.It will lead something error when git-hook be trigged:

``` shell
Error: Could not find "stylelint-config-standard". Do you need the "configBasedir" or "--config-basedir" option?
    at configurationError (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/utils/configurationError.js:12:49)
    at getModulePath (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/utils/getModulePath.js:28:9)
    at loadExtendedConfig (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/augmentConfig.js:216:21)
    at extendConfig (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/augmentConfig.js:184:25)

```

``` shell
$stylelint ./public/static/themes/*.css ./public/static/colorschemes/*.css ./public/static/*.js --config-basedir=./

Error: Could not find "postcss-lit". Do you need the "configBasedir" or "--config-basedir" option?
    at configurationError (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/utils/configurationError.js:12:49)
    at getModulePath (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/utils/getModulePath.js:28:9)
    at getCustomSyntax (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/getPostcssResult.js:69:40)
    at getPostcssResult (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/getPostcssResult.js:32:5)
    at lintSource (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/lintSource.js:99:10)
    at async /home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/standalone.js:211:27
    at async Promise.all (index 14)
    at async standalone (/home/workspace/node-v20.9.0-linux-x64/lib/node_modules/stylelint/lib/standalone.js:254:22)

```

Ran successfully after installing `postcss-lit` and `stylelint-config-standard` by running the commands as shown below:

``` shell
npm install -g stylelint stylelint-config-standard 
npm install -g stylelint postcss-lit
```

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to open this issue. We do agree with you after doing tests are ourselves we found a similar issue. Also, since you have agreed to work on this issue. Therefore, we will assign this issue to you right away 🚀 🙂 .
